"""Seed data for demo Knowledge Base and travel services."""

DESTINATIONS = [
    {
        "name": "Đà Lạt",
        "region": "Lâm Đồng",
        "description": "Thành phố ngàn hoa với khí hậu mát mẻ quanh năm, nổi tiếng với đồi thông, hồ nước và kiến trúc Pháp cổ.",
        "highlights": "Hồ Xuân Hương, Thung lũng Tình Yêu, Chợ Đà Lạt, Dinh Bảo Đại, Langbiang",
        "best_season": "Tháng 11 - tháng 3 (hoa dã quỳ, mùa khô mát)",
        "weather": "Nhiệt độ 15-25°C, mát mẻ, sương mù buổi sáng",
        "cuisine": "Bánh căn, bánh tráng nướng, lẩu gà lá é, kem bơ, atiso",
        "budget_low": 2000000,
        "budget_high": 6000000,
        "tags": "núi,nghỉ dưỡng,romantic,khám phá",
        "image_url": "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80",
    },
    {
        "name": "Phú Quốc",
        "region": "Kiên Giang",
        "description": "Đảo ngọc với bãi biển trong xanh, resort sang trọng và hải sản tươi ngon.",
        "highlights": "Bãi Sao, Grand World, VinWonders, Chợ đêm Dinh Cậu, Nhà tù Phú Quốc",
        "best_season": "Tháng 11 - tháng 4 (mùa khô, biển êm)",
        "weather": "Nhiệt độ 27-32°C, nắng đẹp, mùa mưa từ tháng 5-10",
        "cuisine": "Gỏi cá trích, nhum biển nướng, bún quậy Kiến Xây, hải sản tươi",
        "budget_low": 4000000,
        "budget_high": 15000000,
        "tags": "biển,resort,gia đình,cặp đôi",
        "image_url": "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    },
    {
        "name": "Hà Giang",
        "region": "Hà Giang",
        "description": "Vùng đất địa đầu Tổ quốc với cột mốc Lũng Cú, đèo Mã Pí Lèng hùng vĩ và văn hóa các dân tộc.",
        "highlights": "Cột cờ Lũng Cú, đèo Mã Pí Lèng, Sủng Là, Hoàng Su Phì, cao nguyên đá Đồng Văn",
        "best_season": "Tháng 9 - tháng 11 (hoa tam giác mạch), tháng 3-5 (hoa đào)",
        "weather": "Mát mẻ vùng núi, sương mù, nhiệt độ 10-25°C tùy mùa",
        "cuisine": "Thắng cố, bánh tam giác mạch, thịt trâu gác bếp, rượu ngô",
        "budget_low": 3000000,
        "budget_high": 8000000,
        "tags": "núi,khám phá,solo,phiêu lưu",
        "image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    },
    {
        "name": "Hội An",
        "region": "Quảng Nam",
        "description": "Phố cổ UNESCO với đèn lồng lung linh, kiến trúc cổ kính và ẩm thực đa dạng.",
        "highlights": "Phố cổ, chùa Cầu, An Bàng, làng gốm Thanh Hà, đèn lồng",
        "best_season": "Tháng 2 - tháng 4 (mát mẻ, ít mưa)",
        "weather": "Nhiệt độ 22-30°C, mùa mưa từ tháng 9-12",
        "cuisine": "Cao lầu, mì Quảng, bánh mì Phượng, bánh bao bánh vạc",
        "budget_low": 2500000,
        "budget_high": 7000000,
        "tags": "văn hóa,cặp đôi,ẩm thực,khám phá",
        "image_url": "https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80",
    },
    {
        "name": "Nha Trang",
        "region": "Khánh Hòa",
        "description": "Thành phố biển năng động với VinWonders, tắm biển và ẩm thực hải sản phong phú.",
        "highlights": "VinWonders, Tháp Bà Ponagar, Hòn Mun, Bãi Tranh",
        "best_season": "Tháng 1 - tháng 8",
        "weather": "Nhiệt độ 26-32°C, nắng đẹp",
        "cuisine": "Bún cá Nha Trang, nem nướng, bánh căn chả cá",
        "budget_low": 3000000,
        "budget_high": 10000000,
        "tags": "biển,gia đình,resort",
        "image_url": "https://images.unsplash.com/photo-1559592413-7cec025d7d8e?w=800&q=80",
    },
    {
        "name": "Sa Pa",
        "region": "Lào Cai",
        "description": "Thị trấn sương mù trên núi Fansipan với ruộng bậc thang và văn hóa dân tộc thiểu số.",
        "highlights": "Fansipan, Cát Cát, Ta Phin, ruộng bậc thang Mù Cang Chải",
        "best_season": "Tháng 9 - tháng 11 (lúa chín), tháng 12-2 (tuyết)",
        "weather": "Mát lạnh 8-20°C, sương mù dày",
        "cuisine": "Thịt trâu gác bếp, cá hồi, rượu táo mèo",
        "budget_low": 2500000,
        "budget_high": 7000000,
        "tags": "núi,khám phá,solo,phiêu lưu",
        "image_url": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80",
    },
]

KNOWLEDGE_ENTRIES = [
    {
        "title": "Thời tiết Đà Lạt theo mùa",
        "category": "weather",
        "destination": "Đà Lạt",
        "content": "Đà Lạt có khí hậu mát mẻ quanh năm. Mùa khô (tháng 11-3): nắng đẹp, hoa dã quỳ nở rộ tháng 11-12. Mùa mưa (tháng 4-10): mưa chiều, sương mù dày buổi sáng. Nhiệt độ trung bình 15-25°C.",
        "tags": "thời tiết,mùa du lịch,đà lạt",
    },
    {
        "title": "Chi phí du lịch Phú Quốc 3 ngày 2 đêm",
        "category": "budget",
        "destination": "Phú Quốc",
        "content": "Ngân sách tiết kiệm: 3-5 triệu/người (homestay, ăn quán). Tầm trung: 6-10 triệu (khách sạn 3-4 sao, tour). Cao cấp: 12-20 triệu (resort 5 sao, VinWonders). Vé máy bay khứ hồi SGN-PQC: 1.5-3 triệu.",
        "tags": "chi phí,ngân sách,phú quốc",
    },
    {
        "title": "Ẩm thực Hà Giang đặc sắc",
        "category": "cuisine",
        "destination": "Hà Giang",
        "content": "Thắng cố - món ăn truyền thống người Mông. Bánh tam giác mạch - đặc sản mùa thu. Thịt trâu gác bếp - đặc sản cao nguyên. Rượu ngô - thức uống truyền thống.",
        "tags": "ẩm thực,hà giang,đặc sản",
    },
    {
        "title": "Kinh nghiệm du lịch Hội An",
        "category": "tips",
        "destination": "Hội An",
        "content": "Nên đi phố cổ buổi tối để ngắm đèn lồng. Thuê xe đạp khám phá làng gốm Thanh Hà. Mua vé tham quan phố cổ 120.000đ (5 điểm). Tránh mùa mưa bão tháng 9-12.",
        "tags": "kinh nghiệm,hội an,tips",
    },
    {
        "title": "Lịch trình Phú Quốc 3 ngày 2 đêm gia đình",
        "category": "itinerary",
        "destination": "Phú Quốc",
        "content": "Ngày 1: Đáp sân bay, nhận phòng, Grand World buổi chiều, chợ đêm Dinh Cậu. Ngày 2: Bãi Sao sáng, VinWonders cả ngày. Ngày 3: Nhà tù Phú Quốc, mua quà, ra sân bay.",
        "tags": "lịch trình,phú quốc,gia đình,3 ngày 2 đêm",
    },
    {
        "title": "Lịch trình Đà Lạt 2 ngày 1 đêm cặp đôi",
        "category": "itinerary",
        "destination": "Đà Lạt",
        "content": "Ngày 1: Hồ Xuân Hương, Dinh Bảo Đại, Thung lũng Tình Yêu, chợ đêm. Ngày 2: Langbiang sáng sớm, cafe view đẹp, về.",
        "tags": "lịch trình,đà lạt,cặp đôi,2 ngày 1 đêm",
    },
    {
        "title": "Phương tiện di chuyển Hà Giang",
        "category": "transport",
        "destination": "Hà Giang",
        "content": "Từ Hà Nội: xe khách giường nằm 8-10 tiếng (250-350k). Thuê xe máy tại Hà Giang: 150-200k/ngày. Tour xe ô tô 3 ngày: 2-3 triệu/người. Lưu ý: đèo dốc, cần kinh nghiệm lái xe.",
        "tags": "di chuyển,hà giang,xe máy",
    },
    {
        "title": "Điểm đến phù hợp ngân sách thấp",
        "category": "recommendation",
        "destination": "",
        "content": "Ngân sách dưới 3 triệu: Đà Lạt, Ninh Bình, Vũng Tàu. 3-5 triệu: Hội An, Nha Trang, Sa Pa. Trên 5 triệu: Phú Quốc, Đà Nẵng-Hội An combo.",
        "tags": "tư vấn,ngân sách,điểm đến",
    },
    {
        "title": "Điểm đến theo sở thích biển",
        "category": "recommendation",
        "destination": "",
        "content": "Biển đẹp: Phú Quốc, Nha Trang, Quy Nhon, Phú Yên. Biển yên tĩnh: Côn Đảo, Bình Ba. Biển gần HCM: Vũng Tàu, Mũi Né.",
        "tags": "tư vấn,biển,sở thích",
    },
    {
        "title": "Điểm đến theo sở thích núi",
        "category": "recommendation",
        "destination": "",
        "content": "Núi cao: Fansipan Sa Pa, Langbiang Đà Lạt. Trekking: Hà Giang, Pu Luong. Ruộng bậc thang: Mù Cang Chải, Hoàng Su Phì.",
        "tags": "tư vấn,núi,sở thích",
    },
]

HOTELS = [
    {"name": "Dalat Palace Heritage Hotel", "destination": "Đà Lạt", "type": "hotel", "price_per_night": 2500000, "rating": 4.8, "address": "12 Trần Phú, Đà Lạt", "amenities": "Spa, Pool, Restaurant"},
    {"name": "Homestay The Kupid", "destination": "Đà Lạt", "type": "homestay", "price_per_night": 600000, "rating": 4.5, "address": "Ward 5, Đà Lạt", "amenities": "View đồi thông, Cafe"},
    {"name": "JW Marriott Phu Quoc", "destination": "Phú Quốc", "type": "resort", "price_per_night": 8500000, "rating": 4.9, "address": "Bai Khem, Phú Quốc", "amenities": "Beach, Spa, Pool"},
    {"name": "Homestay Mango Bay", "destination": "Phú Quốc", "type": "homestay", "price_per_night": 800000, "rating": 4.3, "address": "Bãi Trường, Phú Quốc", "amenities": "Gần biển, BBQ"},
    {"name": "Hoi An Ancient House", "destination": "Hội An", "type": "homestay", "price_per_night": 900000, "rating": 4.6, "address": "Phố cổ Hội An", "amenities": "Kiến trúc cổ, Bike rental"},
    {"name": "Sapa Clay House", "destination": "Sa Pa", "type": "homestay", "price_per_night": 700000, "rating": 4.4, "address": "Ta Van, Sa Pa", "amenities": "View ruộng bậc thang"},
]

TOURS = [
    {"name": "Tour Bắc Đảo Phú Quốc 1 ngày", "destination": "Phú Quốc", "duration": "1 ngày", "price": 650000, "description": "Vinpearl Safari, Gành Dầu, Bãi Dài", "includes": "Xe, HDV, ăn trưa"},
    {"name": "Tour 3 Đảo Nha Trang", "destination": "Nha Trang", "duration": "1 ngày", "price": 550000, "description": "Hòn Mun, Hòn Tằm, lặn ngắm san hô", "includes": "Cano, lặn, ăn trưa"},
    {"name": "Tour Hà Giang Loop 3 ngày", "destination": "Hà Giang", "duration": "3 ngày", "price": 3200000, "description": "Lũng Cú, Mã Pí Lèng, Đồng Văn", "includes": "Xe máy, homestay, ăn uống"},
    {"name": "Tour Đà Lạt City 1 ngày", "destination": "Đà Lạt", "duration": "1 ngày", "price": 450000, "description": "Langbiang, Dinh Bảo Đại, Thung lũng Tình Yêu", "includes": "Xe, HDV, vé tham quan"},
    {"name": "Tour Hội An - Rừng dừa 1 ngày", "destination": "Hội An", "duration": "1 ngày", "price": 500000, "description": "Rừng dừa Bảy Mẫu, làng gốm Thanh Hà", "includes": "Thuyền thúng, HDV"},
]

TICKETS = [
    {"name": "VinWonders Phú Quốc", "destination": "Phú Quốc", "price": 950000, "description": "Vé công viên giải trí cả ngày"},
    {"name": "Grand World Phú Quốc", "destination": "Phú Quốc", "price": 0, "description": "Miễn phí vào cổng, trả phí trò chơi"},
    {"name": "Vinpearl Safari Phú Quốc", "destination": "Phú Quốc", "price": 750000, "description": "Safari bán hoang dã"},
    {"name": "Vé tham quan Phố cổ Hội An", "destination": "Hội An", "price": 120000, "description": "5 điểm tham quan trong phố cổ"},
    {"name": "Cáp treo Fansipan", "destination": "Sa Pa", "price": 900000, "description": "Vé cáp treo khứ hồi lên đỉnh Fansipan"},
    {"name": "VinWonders Nha Trang", "destination": "Nha Trang", "price": 880000, "description": "Công viên giải trí trên đảo Hòn Tre"},
]

USERS = [
    {"name": "Admin", "email": "admin@travel.ai", "password": "admin123", "role": "admin"},
    {"name": "Nguyễn Văn A", "email": "user@travel.ai", "password": "user123", "role": "user"},
    {"name": "Trần Thị B", "email": "demo@travel.ai", "password": "demo123", "role": "user"},
]
