-- 13_seed_content_options.sql — seed taxonomy (idempotent).
BEGIN;
INSERT INTO content_options (content_type, field, code, label, sort_order) VALUES
('destinations','type','attraction','Điểm tham quan',0),
('destinations','type','nature','Thiên nhiên',1),
('destinations','type','mountain','Núi / Đồi',2),
('destinations','type','beach','Bãi biển',3),
('destinations','type','museum','Bảo tàng',4),
('destinations','type','temple','Đền / Chùa',5),
('destinations','type','entertainment','Giải trí',6),
('destinations','type','amusement_park','Công viên giải trí',7),
('destinations','type','theme_park','Công viên chủ đề',8),
('destinations','type','water_park','Công viên nước',9),
('destinations','type','aquarium','Thủy cung',10),
('destinations','type','zoo','Vườn thú',11),
('destinations','type','kids_zone','Khu vui chơi trẻ em',12),
('destinations','type','cultural_village','Làng văn hóa',13),
('destinations','type','culture','Văn hóa',14),
('destinations','type','heritage','Di sản',15),
('destinations','type','market','Chợ',16),
('destinations','type','border_crossing','Cửa khẩu',17),
('foods','type','main_dish','Món chính',0),
('foods','type','specialty','Đặc sản',1),
('foods','type','snack','Ăn vặt',2),
('foods','type','dessert','Tráng miệng',3),
('foods','type','seafood','Hải sản',4),
('foods','type','noodle','Món sợi (bún/phở/mì)',5),
('foods','type','soup','Món canh / súp',6),
('foods','type','beef','Món bò',7),
('foods','type','fruit','Trái cây',8),
('foods','type','drink','Đồ uống',9),
('foods','type','beverage','Đồ uống',10),
('foods','type','condiment','Gia vị',11),
('foods','type','market','Chợ',12),
('restaurants','cuisine_type','restaurant','Nhà hàng',0),
('restaurants','cuisine_type','cafe','Quán cà phê',1),
('restaurants','cuisine_type','street_food','Ăn đường phố',2),
('restaurants','cuisine_type','market_stall','Quầy chợ',3),
('shopping','goods_type','market','Chợ',0),
('shopping','goods_type','mall','Trung tâm thương mại',1),
('shopping','goods_type','specialty_store','Cửa hàng đặc sản',2),
('shopping','goods_type','street','Phố mua sắm',3),
('shopping','goods_type','other','Khác',4),
('transport','vehicle','motorbike','Xe máy',0),
('transport','vehicle','motorbike_rental','Thuê xe máy',1),
('transport','vehicle','car','Ô tô',2),
('transport','vehicle','car_rental','Thuê ô tô',3),
('transport','vehicle','private_car','Xe riêng',4),
('transport','vehicle','taxi','Taxi',5),
('transport','vehicle','grab','Grab',6),
('transport','vehicle','taxi_grab','Taxi / Grab',7),
('transport','vehicle','bus','Xe buýt',8),
('transport','vehicle','bus_combined','Xe buýt (kết hợp)',9),
('transport','vehicle','bus_noi_dao','Xe buýt nội đảo',10),
('transport','vehicle','train','Tàu hỏa',11),
('transport','vehicle','airplane','Máy bay',12),
('transport','vehicle','flight','Chuyến bay',13),
('transport','vehicle','bicycle','Xe đạp',14),
('transport','vehicle','walking','Đi bộ',15),
('transport','vehicle','boat','Thuyền',16),
('transport','vehicle','ferry','Phà',17),
('transport','vehicle','boat_ferry','Phà / Thuyền',18),
('transport','vehicle','cruise_boat','Du thuyền',19),
('transport','vehicle','electric_car','Xe điện',20),
('transport','vehicle','xe_om','Xe ôm',21),
('transport','vehicle','xe_dien_golf','Xe điện (sân golf)',22),
('transport','vehicle','motorbike_or_car','Xe máy / Ô tô',23),
('transport','vehicle','other','Khác',24),
('tours','type','solo','Một mình',0),
('tours','type','couple','Cặp đôi',1),
('tours','type','family','Gia đình',2),
('tours','type','group','Nhóm',3),
('events','type','festival','Lễ hội',0),
('events','type','culture','Văn hóa',1),
('events','type','sport','Thể thao',2),
('events','type','music','Âm nhạc',3),
('events','type','food','Ẩm thực',4)
ON CONFLICT (content_type, field, code) DO UPDATE SET label = EXCLUDED.label, sort_order = EXCLUDED.sort_order, is_active = TRUE;
COMMIT;
SELECT content_type, count(*) FROM content_options GROUP BY 1 ORDER BY 1;
